libvirt:
  box: CentOS-7
  box_url: https://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7.LibVirt.box
  default_prefix: kube
  private_net_name: kube
  storage_pool_name: default
  suspend_mode: managedsave

common:
  ip_address_net_24: 192.168.10

master:
  count: 1
  ip_address_start: 10

node:
  count: 2
  ip_address_start: 20
